//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34003
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Win32.TaskScheduler.Properties
{
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mygod.WifiShare._References_._TaskScheduler_.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Call a COM object 的本地化字符串。
        /// </summary>
        internal static string ActionTypeComHandler {
            get {
                return ResourceManager.GetString("ActionTypeComHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start a program 的本地化字符串。
        /// </summary>
        internal static string ActionTypeExecute {
            get {
                return ResourceManager.GetString("ActionTypeExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send an e-mail 的本地化字符串。
        /// </summary>
        internal static string ActionTypeSendEmail {
            get {
                return ResourceManager.GetString("ActionTypeSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display a message 的本地化字符串。
        /// </summary>
        internal static string ActionTypeShowMessage {
            get {
                return ResourceManager.GetString("ActionTypeShowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的本地化字符串。
        /// </summary>
        internal static string ComHandlerAction {
            get {
                return ResourceManager.GetString("ComHandlerAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 every day 的本地化字符串。
        /// </summary>
        internal static string DOWAllDays {
            get {
                return ResourceManager.GetString("DOWAllDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {1} {0} 的本地化字符串。
        /// </summary>
        internal static string EmailAction {
            get {
                return ResourceManager.GetString("EmailAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 . 的本地化字符串。
        /// </summary>
        internal static string EndSentence {
            get {
                return ResourceManager.GetString("EndSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} {1} 的本地化字符串。
        /// </summary>
        internal static string ExecAction {
            get {
                return ResourceManager.GetString("ExecAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  - 的本地化字符串。
        /// </summary>
        internal static string HyphenSeparator {
            get {
                return ResourceManager.GetString("HyphenSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ,  的本地化字符串。
        /// </summary>
        internal static string ListSeparator {
            get {
                return ResourceManager.GetString("ListSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 every month 的本地化字符串。
        /// </summary>
        internal static string MOYAllMonths {
            get {
                return ResourceManager.GetString("MOYAllMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple actions defined 的本地化字符串。
        /// </summary>
        internal static string MultipleActions {
            get {
                return ResourceManager.GetString("MultipleActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple triggers defined 的本地化字符串。
        /// </summary>
        internal static string MultipleTriggers {
            get {
                return ResourceManager.GetString("MultipleTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的本地化字符串。
        /// </summary>
        internal static string ShowMessageAction {
            get {
                return ResourceManager.GetString("ShowMessageAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Author 的本地化字符串。
        /// </summary>
        internal static string TaskDefaultPrincipal {
            get {
                return ResourceManager.GetString("TaskDefaultPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        internal static string TaskStateDisabled {
            get {
                return ResourceManager.GetString("TaskStateDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Queued 的本地化字符串。
        /// </summary>
        internal static string TaskStateQueued {
            get {
                return ResourceManager.GetString("TaskStateQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready 的本地化字符串。
        /// </summary>
        internal static string TaskStateReady {
            get {
                return ResourceManager.GetString("TaskStateReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Running 的本地化字符串。
        /// </summary>
        internal static string TaskStateRunning {
            get {
                return ResourceManager.GetString("TaskStateRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string TaskStateUnknown {
            get {
                return ResourceManager.GetString("TaskStateUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 any user 的本地化字符串。
        /// </summary>
        internal static string TriggerAnyUser {
            get {
                return ResourceManager.GetString("TriggerAnyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At system startup 的本地化字符串。
        /// </summary>
        internal static string TriggerBoot1 {
            get {
                return ResourceManager.GetString("TriggerBoot1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Trigger 的本地化字符串。
        /// </summary>
        internal static string TriggerCustom1 {
            get {
                return ResourceManager.GetString("TriggerCustom1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At {0:t} every day 的本地化字符串。
        /// </summary>
        internal static string TriggerDaily1 {
            get {
                return ResourceManager.GetString("TriggerDaily1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At {0:t} every {1} days 的本地化字符串。
        /// </summary>
        internal static string TriggerDaily2 {
            get {
                return ResourceManager.GetString("TriggerDaily2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  indefinitely 的本地化字符串。
        /// </summary>
        internal static string TriggerDuration0 {
            get {
                return ResourceManager.GetString("TriggerDuration0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  for a duration of {0} 的本地化字符串。
        /// </summary>
        internal static string TriggerDurationNot0 {
            get {
                return ResourceManager.GetString("TriggerDurationNot0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Trigger expires at {0:G}. 的本地化字符串。
        /// </summary>
        internal static string TriggerEndBoundary {
            get {
                return ResourceManager.GetString("TriggerEndBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom event filter 的本地化字符串。
        /// </summary>
        internal static string TriggerEvent1 {
            get {
                return ResourceManager.GetString("TriggerEvent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On event - Log: {0} 的本地化字符串。
        /// </summary>
        internal static string TriggerEventBasic1 {
            get {
                return ResourceManager.GetString("TriggerEventBasic1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , Source: {0} 的本地化字符串。
        /// </summary>
        internal static string TriggerEventBasic2 {
            get {
                return ResourceManager.GetString("TriggerEventBasic2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , EventID: {0} 的本地化字符串。
        /// </summary>
        internal static string TriggerEventBasic3 {
            get {
                return ResourceManager.GetString("TriggerEventBasic3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When computer is idle 的本地化字符串。
        /// </summary>
        internal static string TriggerIdle1 {
            get {
                return ResourceManager.GetString("TriggerIdle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At log on of {0} 的本地化字符串。
        /// </summary>
        internal static string TriggerLogon1 {
            get {
                return ResourceManager.GetString("TriggerLogon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At {0:t} on day {1} of {2}, starting {0:d} 的本地化字符串。
        /// </summary>
        internal static string TriggerMonthly1 {
            get {
                return ResourceManager.GetString("TriggerMonthly1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At {0:t} on the {1} {2:f} each {3}, starting {0:d} 的本地化字符串。
        /// </summary>
        internal static string TriggerMonthlyDOW1 {
            get {
                return ResourceManager.GetString("TriggerMonthlyDOW1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When the task is created or modified 的本地化字符串。
        /// </summary>
        internal static string TriggerRegistration1 {
            get {
                return ResourceManager.GetString("TriggerRegistration1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  After triggered, repeat every {0}{1}. 的本地化字符串。
        /// </summary>
        internal static string TriggerRepetition {
            get {
                return ResourceManager.GetString("TriggerRepetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On local connection to {0}. 的本地化字符串。
        /// </summary>
        internal static string TriggerSessionConsoleConnect {
            get {
                return ResourceManager.GetString("TriggerSessionConsoleConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On local disconnect from {0}. 的本地化字符串。
        /// </summary>
        internal static string TriggerSessionConsoleDisconnect {
            get {
                return ResourceManager.GetString("TriggerSessionConsoleDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On remote connection to {0}. 的本地化字符串。
        /// </summary>
        internal static string TriggerSessionRemoteConnect {
            get {
                return ResourceManager.GetString("TriggerSessionRemoteConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On remote disconnect from {0}. 的本地化字符串。
        /// </summary>
        internal static string TriggerSessionRemoteDisconnect {
            get {
                return ResourceManager.GetString("TriggerSessionRemoteDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On workstation lock of {0}. 的本地化字符串。
        /// </summary>
        internal static string TriggerSessionSessionLock {
            get {
                return ResourceManager.GetString("TriggerSessionSessionLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On workstation unlock of {0}. 的本地化字符串。
        /// </summary>
        internal static string TriggerSessionSessionUnlock {
            get {
                return ResourceManager.GetString("TriggerSessionSessionUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 user session of {0} 的本地化字符串。
        /// </summary>
        internal static string TriggerSessionUserSession {
            get {
                return ResourceManager.GetString("TriggerSessionUserSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At {0:t} on {0:d} 的本地化字符串。
        /// </summary>
        internal static string TriggerTime1 {
            get {
                return ResourceManager.GetString("TriggerTime1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At startup 的本地化字符串。
        /// </summary>
        internal static string TriggerTypeBoot {
            get {
                return ResourceManager.GetString("TriggerTypeBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Trigger 的本地化字符串。
        /// </summary>
        internal static string TriggerTypeCustom {
            get {
                return ResourceManager.GetString("TriggerTypeCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Daily 的本地化字符串。
        /// </summary>
        internal static string TriggerTypeDaily {
            get {
                return ResourceManager.GetString("TriggerTypeDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On an event 的本地化字符串。
        /// </summary>
        internal static string TriggerTypeEvent {
            get {
                return ResourceManager.GetString("TriggerTypeEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On idle 的本地化字符串。
        /// </summary>
        internal static string TriggerTypeIdle {
            get {
                return ResourceManager.GetString("TriggerTypeIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At log on 的本地化字符串。
        /// </summary>
        internal static string TriggerTypeLogon {
            get {
                return ResourceManager.GetString("TriggerTypeLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monthly 的本地化字符串。
        /// </summary>
        internal static string TriggerTypeMonthly {
            get {
                return ResourceManager.GetString("TriggerTypeMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monthly 的本地化字符串。
        /// </summary>
        internal static string TriggerTypeMonthlyDOW {
            get {
                return ResourceManager.GetString("TriggerTypeMonthlyDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At task creation/modification 的本地化字符串。
        /// </summary>
        internal static string TriggerTypeRegistration {
            get {
                return ResourceManager.GetString("TriggerTypeRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On state change 的本地化字符串。
        /// </summary>
        internal static string TriggerTypeSessionStateChange {
            get {
                return ResourceManager.GetString("TriggerTypeSessionStateChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One time 的本地化字符串。
        /// </summary>
        internal static string TriggerTypeTime {
            get {
                return ResourceManager.GetString("TriggerTypeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weekly 的本地化字符串。
        /// </summary>
        internal static string TriggerTypeWeekly {
            get {
                return ResourceManager.GetString("TriggerTypeWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At {0:t} every {1} of every week, starting {0:d} 的本地化字符串。
        /// </summary>
        internal static string TriggerWeekly1Week {
            get {
                return ResourceManager.GetString("TriggerWeekly1Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At {0:t} every {1} of every {2} weeks, starting {0:d} 的本地化字符串。
        /// </summary>
        internal static string TriggerWeeklyMultWeeks {
            get {
                return ResourceManager.GetString("TriggerWeeklyMultWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 every 的本地化字符串。
        /// </summary>
        internal static string WWAllWeeks {
            get {
                return ResourceManager.GetString("WWAllWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 fifth 的本地化字符串。
        /// </summary>
        internal static string WWFifthWeek {
            get {
                return ResourceManager.GetString("WWFifthWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 first 的本地化字符串。
        /// </summary>
        internal static string WWFirstWeek {
            get {
                return ResourceManager.GetString("WWFirstWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 fourth 的本地化字符串。
        /// </summary>
        internal static string WWFourthWeek {
            get {
                return ResourceManager.GetString("WWFourthWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 last 的本地化字符串。
        /// </summary>
        internal static string WWLastWeek {
            get {
                return ResourceManager.GetString("WWLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 second 的本地化字符串。
        /// </summary>
        internal static string WWSecondWeek {
            get {
                return ResourceManager.GetString("WWSecondWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 third 的本地化字符串。
        /// </summary>
        internal static string WWThirdWeek {
            get {
                return ResourceManager.GetString("WWThirdWeek", resourceCulture);
            }
        }
    }
}
