//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34003
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mygod.WifiShare {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mygod.WifiShare.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 修改吗？(Y确定，其他取消) 的本地化字符串。
        /// </summary>
        internal static string AskChange {
            get {
                return ResourceManager.GetString("AskChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动状态下拒绝检测！ 的本地化字符串。
        /// </summary>
        internal static string AutoNoCheckingSupport {
            get {
                return ResourceManager.GetString("AutoNoCheckingSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动状态下拒绝初始化设置！ 的本地化字符串。
        /// </summary>
        internal static string AutoNoInit {
            get {
                return ResourceManager.GetString("AutoNoInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动状态下拒绝设置自动启动！ 的本地化字符串。
        /// </summary>
        internal static string AutoNoSettingAutoRun {
            get {
                return ResourceManager.GetString("AutoNoSettingAutoRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动状态下拒绝设置！ 的本地化字符串。
        /// </summary>
        internal static string AutoNoSettings {
            get {
                return ResourceManager.GetString("AutoNoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动状态下拒绝显示帮助！ 的本地化字符串。
        /// </summary>
        internal static string AutoNoShowingHelp {
            get {
                return ResourceManager.GetString("AutoNoShowingHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改自动运行完成。 的本地化字符串。
        /// </summary>
        internal static string ChangeAutoRunFinish {
            get {
                return ResourceManager.GetString("ChangeAutoRunFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置 Microsoft 托管网络虚拟适配器中…… 的本地化字符串。
        /// </summary>
        internal static string ConfiguringVirtualAdapter {
            get {
                return ResourceManager.GetString("ConfiguringVirtualAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}. {1} ({2}) 的本地化字符串。
        /// </summary>
        internal static string ConnectionFormat {
            get {
                return ResourceManager.GetString("ConnectionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AwesomePassword 的本地化字符串。
        /// </summary>
        internal static string DefaultKey {
            get {
                return ResourceManager.GetString("DefaultKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mygod Hotspot 的本地化字符串。
        /// </summary>
        internal static string DefaultSSID {
            get {
                return ResourceManager.GetString("DefaultSSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 三、开机自动启动无线网络共享
        ///0. 启动本软件。
        ///1. 输入T，如看到“当前设置自动启动无线网络共享。”的字样，关闭本程序，否则执行第2步。
        ///2. 输入Y修改成不自动启动无线网络共享。
        ///
        ///四、开机不自动启动无线网络共享
        ///0. 启动本软件。
        ///1. 输入T，如看到“当前设置不自动启动无线网络共享。”的字样，关闭本程序，否则执行第2步。
        ///2. 输入Y修改成自动启动无线网络共享。
        ///
        ///五、可能碰到的问题：
        ///①执行 一.2 时出现“无法启动承载网络。组或资源的状态不是执行请求操作的正确状态。”字样：
        ///　这可能是由于您的 Wi-Fi 没有打开，或者硬件开关被关闭导致，要解决只需打开即可。也有可能是无线网卡正在被使用导致的，这种情况下可以尝试以下步骤解决问题。
        ///　　1. 点击右下角的“网络与共享中心”，如果当前连接到某无线网络，则选中当前连接到的无线网络，点击“断开”并执行第4步，否则执行第3步。
        ///　　2. 打开“控制面板 - 网络和 Internet - 网络和共享中心 - 更改适配器设置”，禁用除了你当前的上网连接（如“本地连接”“宽带连接”）以外的所有连接并重新启用再试。
        ///　　3. 再次执 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化设置完成！ 的本地化字符串。
        /// </summary>
        internal static string InitFinished {
            get {
                return ResourceManager.GetString("InitFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前设置{0}自动启动无线网络共享。 的本地化字符串。
        /// </summary>
        internal static string IsAutoRun {
            get {
                return ResourceManager.GetString("IsAutoRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的网卡{0}支持无线网络共享。 的本地化字符串。
        /// </summary>
        internal static string IsSupport {
            get {
                return ResourceManager.GetString("IsSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有可用的网络连接！ 的本地化字符串。
        /// </summary>
        internal static string NoAvailableConnection {
            get {
                return ResourceManager.GetString("NoAvailableConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不 的本地化字符串。
        /// </summary>
        internal static string Not {
            get {
                return ResourceManager.GetString("Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本程序必须在 Windows 7 或更高版本的 Windows 下运行！
        ///按任意键退出此程序。 的本地化字符串。
        /// </summary>
        internal static string OSError {
            get {
                return ResourceManager.GetString("OSError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择要共享的网络连接序号：（即前面的序号，输个错误的取消操作） 的本地化字符串。
        /// </summary>
        internal static string PickConnectionPrompt {
            get {
                return ResourceManager.GetString("PickConnectionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mygod 的本地化字符串。
        /// </summary>
        internal static string Producer {
            get {
                return ResourceManager.GetString("Producer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 Microsoft 托管网络虚拟适配器具体配置失败！请先启动无线网络共享后再试。 的本地化字符串。
        /// </summary>
        internal static string QueryVirtualAdapterConfigurationFailed {
            get {
                return ResourceManager.GetString("QueryVirtualAdapterConfigurationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 Microsoft 托管网络虚拟适配器失败！请先启动无线网络共享后再试。 的本地化字符串。
        /// </summary>
        internal static string QueryVirtualAdapterFailed {
            get {
                return ResourceManager.GetString("QueryVirtualAdapterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一、第一次使用：输入S对无线网络名和密码进行设置，输入B启动无线网络共享，如果跳出网络选择，请选择家庭网络或工作网络，输入I并按照提示进行第一次配置。
        ///
        ///二、再次使用：只需输入B启动无线网络共享即可。 的本地化字符串。
        /// </summary>
        internal static string QuickHelp {
            get {
                return ResourceManager.GetString("QuickHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 需求配置：
        /// ※ 安装 .NET Framework 4.5.1 或更高（Windows 8.1 自带）
        /// ※ Windows 7 或更高版本的 Windows
        /// ※ 连接到 Internet
        /// ※ 有支持无线网络共享（按 X 检测）的 Wi-Fi 无线网络适配器 的本地化字符串。
        /// </summary>
        internal static string Requirement {
            get {
                return ResourceManager.GetString("Requirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索可用网络连接中…… 的本地化字符串。
        /// </summary>
        internal static string SearchingAvailableNetwork {
            get {
                return ResourceManager.GetString("SearchingAvailableNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启服务时出现错误：{0} 的本地化字符串。
        /// </summary>
        internal static string ServiceError {
            get {
                return ResourceManager.GetString("ServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎进入设置界面，输入您的新的设置，为空则不修改。 的本地化字符串。
        /// </summary>
        internal static string SettingsStep1 {
            get {
                return ResourceManager.GetString("SettingsStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧的无线网络名： 的本地化字符串。
        /// </summary>
        internal static string SettingsStep2 {
            get {
                return ResourceManager.GetString("SettingsStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新的无线网络名： 的本地化字符串。
        /// </summary>
        internal static string SettingsStep3 {
            get {
                return ResourceManager.GetString("SettingsStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧的无线密码： 的本地化字符串。
        /// </summary>
        internal static string SettingsStep4 {
            get {
                return ResourceManager.GetString("SettingsStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新的无线密码： 的本地化字符串。
        /// </summary>
        internal static string SettingsStep5 {
            get {
                return ResourceManager.GetString("SettingsStep5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改完毕，是否要立即生效？(Y生效，其他键不生效) 的本地化字符串。
        /// </summary>
        internal static string SettingsStep6 {
            get {
                return ResourceManager.GetString("SettingsStep6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共享唯一可用的网络连接中…… 的本地化字符串。
        /// </summary>
        internal static string SharingOnlyConnection {
            get {
                return ResourceManager.GetString("SharingOnlyConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在启动服务 {0} …… 的本地化字符串。
        /// </summary>
        internal static string StartingService {
            get {
                return ResourceManager.GetString("StartingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mygod 为您自动启动无线网络共享。 的本地化字符串。
        /// </summary>
        internal static string StartUpDescription {
            get {
                return ResourceManager.GetString("StartUpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动无线网络共享 的本地化字符串。
        /// </summary>
        internal static string StartUpName {
            get {
                return ResourceManager.GetString("StartUpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在停止服务 {0} …… 的本地化字符串。
        /// </summary>
        internal static string StoppingService {
            get {
                return ResourceManager.GetString("StoppingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        internal static string SupportLength {
            get {
                return ResourceManager.GetString("SupportLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支持的承载网络 的本地化字符串。
        /// </summary>
        internal static string SupportTheBearerNetwork {
            get {
                return ResourceManager.GetString("SupportTheBearerNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监视已连接设备中，按 Ctrl + C 键返回。 的本地化字符串。
        /// </summary>
        internal static string WatchCurrentDevices {
            get {
                return ResourceManager.GetString("WatchCurrentDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎使用 {0}！
        ///可用操作：
        ///    A 查看当前共享的设置与状态            B 启动共享
        ///    C 关闭共享                            D 深度重启共享
        ///    H 更多帮助                            I 初始化设置
        ///    K 刷新安全密钥 (用后需要再次启动共享)
        ///    Q 查看当前已连接的设备                R 重启共享
        ///    S 设置无线网络名 (SSID) 与密码        T 设置开机时自动运行
        ///    U 检查更新                            W 监视当前已连接的设备
        ///    X 检查网卡是否支持共享无线网络        输入其他退出
        ///请输入操作： 的本地化字符串。
        /// </summary>
        internal static string WelcomeToUse {
            get {
                return ResourceManager.GetString("WelcomeToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
