//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18051
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mygod.WifiShare {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mygod.WifiShare.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 由 {1} 于 {2} 为您制作。感谢使用！ 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改吗？(Y确定，其他取消) 的本地化字符串。
        /// </summary>
        internal static string AskChange {
            get {
                return ResourceManager.GetString("AskChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动状态下拒绝检测！ 的本地化字符串。
        /// </summary>
        internal static string AutoNoCheckingSupport {
            get {
                return ResourceManager.GetString("AutoNoCheckingSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动状态下拒绝设置自动启动！ 的本地化字符串。
        /// </summary>
        internal static string AutoNoSettingAutoRun {
            get {
                return ResourceManager.GetString("AutoNoSettingAutoRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动状态下拒绝设置！ 的本地化字符串。
        /// </summary>
        internal static string AutoNoSettings {
            get {
                return ResourceManager.GetString("AutoNoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动状态下拒绝显示帮助！ 的本地化字符串。
        /// </summary>
        internal static string AutoNoShowingHelp {
            get {
                return ResourceManager.GetString("AutoNoShowingHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改自动运行完成。 的本地化字符串。
        /// </summary>
        internal static string ChangeAutoRunFinish {
            get {
                return ResourceManager.GetString("ChangeAutoRunFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AwesomePassword 的本地化字符串。
        /// </summary>
        internal static string DefaultKey {
            get {
                return ResourceManager.GetString("DefaultKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mygod Hotspot 的本地化字符串。
        /// </summary>
        internal static string DefaultSSID {
            get {
                return ResourceManager.GetString("DefaultSSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一、第一次使用：
        ///0. 启动本软件。
        ///1. 输入T，如看到“当前设置自动启动无线网络共享。”的字样，关闭本程序，否则执行第2步。
        ///2. 输入S对无线网络名和密码进行设置。
        ///3. 输入B启动无线网络共享。
        ///4. 如果跳出网络选择，请选择家庭网络或工作网络。
        ///5. 打开“控制面板 - 网络和 Internet - 网络和共享中心 - 更改适配器设置”，重命名有“Microsoft Virtual Wifi Miniport Adapter”字样的无线网络连接为“无线网络共享”（或其他名字）。
        ///6. 右击你当前的上网连接（如“本地连接”“宽带连接”“无线网络连接”等）- 属性 - 共享，选中“允许其他用户通过此计算机的 Internet 连接来连接(N)”与“允许其他网络用户控制或禁用共享的 Internet 连接(O)”，家庭网络连接(H)中选择“无线网络共享”（或者你刚刚重命名的名字）。
        ///7. 如果上一步成功则忽视下面步骤。如果没有成功，请回到“更改适配器设置”右击“无线网络共享”，点击属性，点击“Internet 协议版本 4 (TCP/IPv4)”，点击属性，点击使用下面的 IP 地址，然后 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前设置{0}自动启动无线网络共享。 的本地化字符串。
        /// </summary>
        internal static string IsAutoRun {
            get {
                return ResourceManager.GetString("IsAutoRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的网卡{0}支持无线网络共享。 的本地化字符串。
        /// </summary>
        internal static string IsSupport {
            get {
                return ResourceManager.GetString("IsSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不 的本地化字符串。
        /// </summary>
        internal static string Not {
            get {
                return ResourceManager.GetString("Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本程序必须在 Windows 7 或更高版本的 Windows 下运行！
        ///按任意键退出此程序。 的本地化字符串。
        /// </summary>
        internal static string OSError {
            get {
                return ResourceManager.GetString("OSError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mygod 的本地化字符串。
        /// </summary>
        internal static string Producer {
            get {
                return ResourceManager.GetString("Producer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 需求配置：
        /// ※ 安装 .NET Framework 4 Client Profile
        /// ※ Windows 7 或更高版本的 Windows
        /// ※ 连接到 Internet
        /// ※ 有支持无线网络共享（按X检测）的 Wi-fi 无线网络适配器 的本地化字符串。
        /// </summary>
        internal static string ProgramNeeds {
            get {
                return ResourceManager.GetString("ProgramNeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启服务时出现错误：{0} 的本地化字符串。
        /// </summary>
        internal static string ServiceError {
            get {
                return ResourceManager.GetString("ServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎进入设置界面，输入您的新的设置，为空则不修改。 的本地化字符串。
        /// </summary>
        internal static string SettingsStep1 {
            get {
                return ResourceManager.GetString("SettingsStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧的无线网络名： 的本地化字符串。
        /// </summary>
        internal static string SettingsStep2 {
            get {
                return ResourceManager.GetString("SettingsStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新的无线网络名： 的本地化字符串。
        /// </summary>
        internal static string SettingsStep3 {
            get {
                return ResourceManager.GetString("SettingsStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧的无线密码： 的本地化字符串。
        /// </summary>
        internal static string SettingsStep4 {
            get {
                return ResourceManager.GetString("SettingsStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新的无线密码： 的本地化字符串。
        /// </summary>
        internal static string SettingsStep5 {
            get {
                return ResourceManager.GetString("SettingsStep5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改完毕，是否要立即生效？(Y生效，其他键不生效) 的本地化字符串。
        /// </summary>
        internal static string SettingsStep6 {
            get {
                return ResourceManager.GetString("SettingsStep6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在启动服务 {0} …… 的本地化字符串。
        /// </summary>
        internal static string StartingService {
            get {
                return ResourceManager.GetString("StartingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mygod为您自动启动无线网络共享。 的本地化字符串。
        /// </summary>
        internal static string StartUpDescription {
            get {
                return ResourceManager.GetString("StartUpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动无线网络共享 的本地化字符串。
        /// </summary>
        internal static string StartUpName {
            get {
                return ResourceManager.GetString("StartUpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在停止服务 {0} …… 的本地化字符串。
        /// </summary>
        internal static string StoppingService {
            get {
                return ResourceManager.GetString("StoppingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        internal static string SupportLength {
            get {
                return ResourceManager.GetString("SupportLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支持的承载网络 的本地化字符串。
        /// </summary>
        internal static string SupportTheBearerNetwork {
            get {
                return ResourceManager.GetString("SupportTheBearerNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 改进帮助。 的本地化字符串。
        /// </summary>
        internal static string UpdateContent {
            get {
                return ResourceManager.GetString("UpdateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎使用 {0}！
        ///可用操作：A关于，S设置共享SSID与密码，B启动共享，C关闭共享，X检查网卡是否支持共享无线网络，R重启共享，D深度重启共享，U查看本次更新内容，T设置开机时自动运行，H帮助，输入其他退出
        ///请输入操作： 的本地化字符串。
        /// </summary>
        internal static string WelcomeToUse {
            get {
                return ResourceManager.GetString("WelcomeToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
